FROM node:14

WORKDIR /usr/src/app


COPY Mimo/package*.json ./Mimo/


RUN cd Mimo && npm install


COPY Mimo/ ./Mimo/

RUN cd Mimo && npm run build

EXPOSE 3000
CMD ["npm", "start", "--prefix", "Mimo"]  
