version: '3'
services:
  express-app:
    build:
      context: .
      dockerfile: Dockerfile.Express  
    ports:
      - "5000:5000"
    restart: always

  react-app:
    build:
      context: .
      dockerfile: Dockerfile.React
    ports:
      - "5173:5173"
    restart: always
